pipeline {
    agent any

    environment {
          GITHUB_CREDENTIALS_ID = 'github_token'
          REPO_URL = 'https://github.com/Sbajman/python-cicd-app.git'
          SONAR_AUTH_TOKEN = credentials('sonarqube')
          DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
          IMAGE_NAME = 'srraob12/cicd-gitops'
    }
    stages {
          stage('Checkoout') {
            steps {
                script {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [
                            [
                                url: REPO_URL,
                                credentials: GITHUB_CREDENTIALS_ID
                            ]
                        ]
                    ])
                }
            }
          }
          stage('Setup Environment - build') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
          }
          stage('Test') {
            steps {
                sh '''
                .venv/bin/activate'
                pytest
                '''
            }
          }
          stage('Code Analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube') {
                        sh 'sonar-scanner'
                    }
                }
            }
          }
          stage('Quality Gate'){
            steps {
                timeout(time: 10, unit: 'MINUTES') { // Wait up to 10 minutes for the quality gate status
                    def qg = waitForQualityGate()
                    if (qg.status != 'OK') {
                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                    } else {
                        echo "SonarQube Quality Gate passed"
                    }
                }
            }
          }
          stage('Build and Push docker image') {
            steps {
                def comitHash = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                def imageTag = "${comitHash}"
                echo "Image tag: ${imageTag}"
                def imageNameWithTag = "${IMAGE_NAME}:${imageTag}"
                echo "Image name with tag: ${imageNamewithTag}"
                echo "Push image in docker hub"
                docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                     def image= docker.build(imageNameWithTag)
                     image.push()
                }
                env.COMMIT_HASH = commitHash
            }
          }
          stage('Deploy on Dev') {
            steps {
                def containerName = "python-app-container"
                def imageTag = env.COMMIT_HASH

                sh """
                   if [\$(docker ps -q -f name=${containerName})]; then
                      echo "Stopping and removing existing container..."
                      docker stop ${containerName}
                      docker rm ${containerName}
                   fi
                   """

                // Run the container
                sh """
                    echo "Running new container with image tag ${imageTag}..."
                    docker run -d --name ${containerName} -p 8090:8080 ${IMAGE_NAME}: ${imageTag}
                  """
             }
          }
          stage('Health check on Dev') {
            steps {
                echo "Performing health check on Docker Container..."
                sleep(time: 30, unit: "SECONDS")
                def healthurl = "http://host.docker.internal:8090/health"
                def response = sh(script: "curl -s ${healthUrl}", returnStdout: true).trim()
                echo "Response from health check API: ${response}"
                def jsonResponse = readJSON test: response
                def status = jsonResponse.status
                echo "Health Status: ${status}"

                if (status == 'UP') {
                    echo 'Health check passed: Application is healthy.'
                } else {
                    error 'Health check failed: Application is not healthy.'
                }
            }
          }

         post {
            always {
                echo 'Clean up workspaces after build'
                cleanWs()
            }
            success {
                echo 'Pipeline successful'
            }

            failure {
                echo 'Pipeline failed'
            }

         } 
    }
}
