pipeline {
    agent any

    environment {
          GITHUB_CREDENTIALS_ID = 'github-token'
          REPO_URL = 'https://github.com/Sbajman/python-cicd-app.git'
          SONAR_AUTH_TOKEN = credentials('sonarqube')
          DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
          IMAGE_NAME = 'srraob12/cicd-gitops'
    }
    stages {
        //   stage('Checkout') {
        //     steps {
        //         script {
        //             checkout([
        //                 $class: 'GitSCM',
        //                 branches: [[name: '*/main']],
        //                 userRemoteConfigs: [[
        //                     url: REPO_URL,
        //                     credentialsId: GITHUB_CREDENTIALS_ID
        //                 ]]
        //             ])
        //         }
        //     }
        // }

        stage('Setup Environment - build') {
            steps {
                sh '''
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install --upgrade pip
                  pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                  . venv/bin/activate
                  pytest
                '''
            }
        }

        stage('Code Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    echo "Running Sonar Scanner in Docker..."

                    docker run --rm \
                        --network ci \
                        -v "$PWD:/usr/src" \
                        sonarsource/sonar-scanner-cli \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.login='squ_f954bb32da030b6a0f41970d173e694870b171bd' \
                        -Dsonar.projectKey=python-cicd-app \
                        -Dsonar.sources=app \
                        -Dsonar.tests=tests
                    '''
                }
            }
        }

  
        stage('Quality Gate') {
            steps {
                script {
                    timeout(time: 10, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: true
                        echo "SonarQube Quality Gate passed"
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    def commitHash = sh(
                        script: 'git rev-parse --short HEAD',
                        returnStdout: true
                    ).trim()

                    env.COMMIT_HASH = commitHash
                    def imageTag = commitHash
                    def imageNameWithTag = "${IMAGE_NAME}:${imageTag}"

                    echo "Image tag: ${imageTag}"
                    echo "Image name with tag: ${imageNameWithTag}"

                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        def image = docker.build(imageNameWithTag)
                        image.push()
                    }
                }
            }
        }

        stage('Deploy on Dev') {
            steps {
                script {
                    def containerName = "python-app-container"
                    def imageTag = env.COMMIT_HASH

                    sh """
                      if [ \$(docker ps -q -f name=${containerName}) ]; then
                          echo "Stopping and removing existing container..."
                          docker stop ${containerName}
                          docker rm ${containerName}
                      fi
                    """

                    sh """
                      echo "Running new container with image tag ${imageTag}..."
                      docker run -d --name ${containerName} -p 8090:8085 ${IMAGE_NAME}:${imageTag}
                    """
                }
            }
        }

        stage('Health Check on Dev') {
            steps {
                script {
                    echo "Performing health check..."
                    sleep(time: 30, unit: "SECONDS")

                    def healthUrl = "http://host.docker.internal:8090/health"
                    def response = sh(
                        script: "curl -s ${healthUrl}",
                        returnStdout: true
                    ).trim()

                    echo "Response: ${response}"

                    def jsonResponse = readJSON(text: response)
                    def status = jsonResponse.status

                    echo "Health Status: ${status}"

                    if (status == 'ok') {
                        echo "Health check passed"
                    } else {
                        error "Health check failed"
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning workspace'
            cleanWs()
        }
        success {
            echo 'Pipeline successful'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}