apiVersion: v1
stringData:
  password: <Github-PAT>
  url: https://github.com/Sbajman/python-cicd-gitops-pipeline.git 
  username: Sbajman
type: Opaque
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository 